var FFI = require('ffi'),
    ArrayType = require('ref-array'),
    Struct = require('ref-struct'),
    StrictType = require('ref-strict'),
    ref = require('ref');
var voidPtr = ref.refType(ref.types.void);
exports.CONSTANTS = {};
var Reaction_t = exports.Reaction_t = StrictType(voidPtr);
var SBMLNamespaces_t = exports.SBMLNamespaces_t = StrictType(voidPtr);
var XMLNamespaces_t = exports.XMLNamespaces_t = StrictType(voidPtr);
var KineticLaw_t = exports.KineticLaw_t = StrictType(voidPtr);
var SpeciesReference_t = exports.SpeciesReference_t = StrictType(voidPtr);
var ListOf_t = exports.ListOf_t = StrictType(voidPtr);
var ReactionGlyph_t = exports.ReactionGlyph_t = StrictType(voidPtr);
var SpeciesReferenceGlyph_t = exports.SpeciesReferenceGlyph_t = StrictType(voidPtr);
var Curve_t = exports.Curve_t = StrictType(voidPtr);
var LineSegment_t = exports.LineSegment_t = StrictType(voidPtr);
var CubicBezier_t = exports.CubicBezier_t = StrictType(voidPtr);
exports.libsbml = new FFI.Library('libsbml', {
    Reaction_create: [Reaction_t, [ref.types.uint32, ref.types.uint32]],
    Reaction_createWithNS: [Reaction_t, [SBMLNamespaces_t]],
    Reaction_free: [ref.types.void, [Reaction_t]],
    Reaction_clone: [Reaction_t, [Reaction_t]],
    Reaction_initDefaults: [ref.types.void, [Reaction_t]],
    Reaction_getNamespaces: [XMLNamespaces_t, [Reaction_t]],
    Reaction_getId: [ref.types.CString, [Reaction_t]],
    Reaction_getName: [ref.types.CString, [Reaction_t]],
    Reaction_getKineticLaw: [KineticLaw_t, [Reaction_t]],
    Reaction_getReversible: [ref.types.int32, [Reaction_t]],
    Reaction_getFast: [ref.types.int32, [Reaction_t]],
    Reaction_getCompartment: [ref.types.CString, [Reaction_t]],
    Reaction_isSetId: [ref.types.int32, [Reaction_t]],
    Reaction_isSetName: [ref.types.int32, [Reaction_t]],
    Reaction_isSetKineticLaw: [ref.types.int32, [Reaction_t]],
    Reaction_isSetCompartment: [ref.types.int32, [Reaction_t]],
    Reaction_isSetReversible: [ref.types.int32, [Reaction_t]],
    Reaction_isSetFast: [ref.types.int32, [Reaction_t]],
    Reaction_setId: [ref.types.int32, [Reaction_t, ref.types.CString]],
    Reaction_setName: [ref.types.int32, [Reaction_t, ref.types.CString]],
    Reaction_setKineticLaw: [ref.types.int32, [Reaction_t, KineticLaw_t]],
    Reaction_setReversible: [ref.types.int32, [Reaction_t, ref.types.int32]],
    Reaction_setFast: [ref.types.int32, [Reaction_t, ref.types.int32]],
    Reaction_setCompartment: [ref.types.int32, [Reaction_t, ref.types.CString]],
    Reaction_unsetName: [ref.types.int32, [Reaction_t]],
    Reaction_unsetKineticLaw: [ref.types.int32, [Reaction_t]],
    Reaction_unsetFast: [ref.types.int32, [Reaction_t]],
    Reaction_unsetCompartment: [ref.types.int32, [Reaction_t]],
    Reaction_hasRequiredAttributes: [ref.types.int32, [Reaction_t]],
    Reaction_addReactant: [ref.types.int32, [Reaction_t, SpeciesReference_t]],
    Reaction_addProduct: [ref.types.int32, [Reaction_t, SpeciesReference_t]],
    Reaction_addModifier: [ref.types.int32, [Reaction_t, SpeciesReference_t]],
    Reaction_createReactant: [SpeciesReference_t, [Reaction_t]],
    Reaction_createProduct: [SpeciesReference_t, [Reaction_t]],
    Reaction_createModifier: [SpeciesReference_t, [Reaction_t]],
    Reaction_createKineticLaw: [KineticLaw_t, [Reaction_t]],
    Reaction_getListOfReactants: [ListOf_t, [Reaction_t]],
    Reaction_getListOfProducts: [ListOf_t, [Reaction_t]],
    Reaction_getListOfModifiers: [ListOf_t, [Reaction_t]],
    Reaction_getReactant: [SpeciesReference_t, [Reaction_t, ref.types.uint32]],
    Reaction_getReactantBySpecies: [SpeciesReference_t, [Reaction_t, ref.types.CString]],
    Reaction_getProduct: [SpeciesReference_t, [Reaction_t, ref.types.uint32]],
    Reaction_getProductBySpecies: [SpeciesReference_t, [Reaction_t, ref.types.CString]],
    Reaction_getModifier: [SpeciesReference_t, [Reaction_t, ref.types.uint32]],
    Reaction_getModifierBySpecies: [SpeciesReference_t, [Reaction_t, ref.types.CString]],
    Reaction_getNumReactants: [ref.types.uint32, [Reaction_t]],
    Reaction_getNumProducts: [ref.types.uint32, [Reaction_t]],
    Reaction_getNumModifiers: [ref.types.uint32, [Reaction_t]],
    Reaction_removeReactant: [SpeciesReference_t, [Reaction_t, ref.types.uint32]],
    Reaction_removeReactantBySpecies: [SpeciesReference_t, [Reaction_t, ref.types.CString]],
    Reaction_removeProduct: [SpeciesReference_t, [Reaction_t, ref.types.uint32]],
    Reaction_removeProductBySpecies: [SpeciesReference_t, [Reaction_t, ref.types.CString]],
    Reaction_removeModifier: [SpeciesReference_t, [Reaction_t, ref.types.uint32]],
    Reaction_removeModifierBySpecies: [SpeciesReference_t, [Reaction_t, ref.types.CString]],
    ReactionGlyph_create: [ReactionGlyph_t, []],
    ReactionGlyph_createFrom: [ReactionGlyph_t, [ReactionGlyph_t]],
    ReactionGlyph_clear: [ref.types.void, [ReactionGlyph_t]],
    ReactionGlyph_createWith: [ReactionGlyph_t, [ref.types.CString]],
    ReactionGlyph_createWithReactionId: [ReactionGlyph_t, [ref.types.CString, ref.types.CString]],
    ReactionGlyph_free: [ref.types.void, [ReactionGlyph_t]],
    ReactionGlyph_setReactionId: [ref.types.void, [ReactionGlyph_t, ref.types.CString]],
    ReactionGlyph_getReactionId: [ref.types.CString, [ReactionGlyph_t]],
    ReactionGlyph_isSetReactionId: [ref.types.int32, [ReactionGlyph_t]],
    ReactionGlyph_addSpeciesReferenceGlyph: [ref.types.void, [ReactionGlyph_t, SpeciesReferenceGlyph_t]],
    ReactionGlyph_getNumSpeciesReferenceGlyphs: [ref.types.uint32, [ReactionGlyph_t]],
    ReactionGlyph_getSpeciesReferenceGlyph: [SpeciesReferenceGlyph_t, [ReactionGlyph_t, ref.types.uint32]],
    ReactionGlyph_getListOfSpeciesReferenceGlyphs: [ListOf_t, [ReactionGlyph_t]],
    ReactionGlyph_removeSpeciesReferenceGlyph: [SpeciesReferenceGlyph_t, [ReactionGlyph_t, ref.types.uint32]],
    ReactionGlyph_initDefaults: [ref.types.void, [ReactionGlyph_t]],
    ReactionGlyph_setCurve: [ref.types.void, [ReactionGlyph_t, Curve_t]],
    ReactionGlyph_getCurve: [Curve_t, [ReactionGlyph_t]],
    ReactionGlyph_isSetCurve: [ref.types.int32, [ReactionGlyph_t]],
    ReactionGlyph_createSpeciesReferenceGlyph: [SpeciesReferenceGlyph_t, [ReactionGlyph_t]],
    ReactionGlyph_createSpeciesReferenceGlyph: [SpeciesReferenceGlyph_t, [ReactionGlyph_t]],
    ReactionGlyph_createLineSegment: [LineSegment_t, [ReactionGlyph_t]],
    ReactionGlyph_createCubicBezier: [CubicBezier_t, [ReactionGlyph_t]],
    ReactionGlyph_removeSpeciesReferenceGlyph: [SpeciesReferenceGlyph_t, [ReactionGlyph_t, ref.types.uint32]],
    ReactionGlyph_removeSpeciesReferenceGlyphWithId: [SpeciesReferenceGlyph_t, [ReactionGlyph_t, ref.types.CString]],
    ReactionGlyph_getIndexForSpeciesReferenceGlyph: [ref.types.uint32, [ReactionGlyph_t, ref.types.CString]],
    ReactionGlyph_clone: [ReactionGlyph_t, [ReactionGlyph_t]],
});
